# Generated by Django 5.1.7 on 2025-03-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_remove_tarefas_descricao_tarefas_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
    ]
